### 获取用户信息
GET http://localhost:8080/user?id=100


### 获取用户信息
GET http://localhost:8080/find?timeout=1100

### 通过8081调用set Timeout Ports
GET http://localhost:8081/ports?ports=8080,8094


### 修改灰度比例值
GET http://localhost:8080/gray?radio=100



### 获取用户信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}

### 获取订单信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.OrderService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}



### 获取用户信息
POST http://localhost:8082/phoenix-rpc/
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}


### 获取用户信息
POST http://localhost:8080/phoenix-rpc/
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [
    100,
    "zyszero"
  ]
}

