### 获取8080端口的用户信息
GET http://localhost:8080/phoenix-rpc/user?id=100

### 修改灰度比例值
GET http://localhost:8080/phoenix-rpc/gray?radio=100

### 通过8080调用超时接口
GET http://localhost:8080/phoenix-rpc/find?timeout=1100

### 通过8081调用接口，修改超时时间
GET http://localhost:8081/ports?ports=8080,8094

### 通过8081调用配置项接口
GET http://localhost:8081/metas

### 获取用户信息
POST http://localhost:8080/phoenix-rpc
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}

### 获取订单信息
POST http://localhost:8080/phoenix-rpc
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.OrderService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}



### 获取用户信息
POST http://localhost:8082/phoenix-rpc
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}


### 获取用户信息
POST http://localhost:8080/phoenix-rpc
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [
    100,
    "zyszero"
  ]
}

