server:
  port: 8080

phoenix:
  rpc:
    registry:
      zookeeper:
        server: 192.168.200.61:2181
        root: phoenix-rpc


app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000
  
logging:
  level:
    root: error
    cn.zyszero.phoenix.rpc: info